### ISSUE TITLE
Deployment provisioning fails with extension error

### ISSUE THREAD

**Issue by larryms** [Microsoft/Docker-EE-on-Azure-Stack-Deployment#10]
My deployment shows as failed after trying for 1+ hrs; however, it appears to have provisioned the appropriate resources and I can use the docker cluster.

Error shown:

The resource operation completed with terminal provisioning stage 'Failed'
Failed to provision VM extensions for VM 'manager-01' (Code: VMExtensionProvisioningError)

**Comment by stevenfollis** [comment]
Was this from the `master` or `wip` branch? We did some adjustments to the `wip` that swapped out the CSE to v2 and unsure if it made it into master

**Comment by amazaheri** [comment]
Also did you install the extensions to your Azure Stack Marketplace?

**Comment by larryms** [comment]
@stevenfollis , I think I used master, but I will need to go back and check.
I did not put any extensions in the marketplace.
