### ISSUE TITLE
Race condition with NICs and Vnet

### ISSUE THREAD

**Issue by stevenfollis** [Microsoft/Docker-EE-on-Azure-Stack-Deployment#14]
Occasionally the NIC will provision before the Vnet completes, leading to an error due to the subnet not being available. Add a `dependsOn` to each NIC referencing the resourceID of the vnet.

ex:
```
"dependsOn": [
        "[resourceId('Microsoft.Network/virtualNetworks', 'vnet')]",
```

**Comment by amazaheri** [comment]
Thank you @stevenfollis !
